import { ArrowLeft, Dna } from 'lucide-react';

export default function TermsOfService({ navigate }) {
  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#050505', color: '#FAFAFA', fontFamily: 'Inter, sans-serif' }}>
      <nav style={{
        padding: '16px 24px',
        borderBottom: '1px solid rgba(255,255,255,0.1)',
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
      }}>
        <button
          onClick={() => navigate('landing')}
          style={{
            background: 'none',
            border: 'none',
            color: '#A1A1AA',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            fontSize: '14px',
            fontFamily: 'Inter, sans-serif',
            padding: 0,
          }}
        >
          <ArrowLeft size={15} />
          Back
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Dna style={{ color: '#00F0FF', width: 20, height: 20 }} strokeWidth={1.5} />
          <span style={{ fontFamily: 'Manrope, sans-serif', fontWeight: 700, letterSpacing: '-0.025em' }}>MYOGEN</span>
        </div>
      </nav>

      <main style={{ maxWidth: '700px', margin: '0 auto', padding: '56px 24px 80px' }}>
        <h1 style={{ fontFamily: 'Manrope, sans-serif', fontSize: '1.875rem', fontWeight: 700, marginBottom: '8px', letterSpacing: '-0.025em' }}>
          Terms of Service
        </h1>
        <p style={{ color: '#A1A1AA', fontSize: '13px', marginBottom: '48px' }}>Last updated: April 2026</p>

        <Section title="Acceptance of terms">
          By creating an account or using Myogen, you agree to these Terms of Service. If you do not agree, please do
          not use the app. We reserve the right to update these terms at any time — continued use after changes
          constitutes acceptance.
        </Section>

        <Section title="Who may use Myogen">
          You must be at least 16 years old to use Myogen. By using the service you confirm you meet this requirement.
          Myogen is provided for personal, non-commercial use only.
        </Section>

        <Section title="What Myogen provides">
          Myogen is an AI-assisted fitness education platform. Content generated by the app — including physique
          analyses, workout guidance, and nutritional information — is for informational purposes only and does not
          constitute medical or professional fitness advice. Always consult a qualified health professional before
          making changes to your exercise or diet.
        </Section>

        <Section title="Accounts">
          You are responsible for keeping your account credentials secure and for all activity that occurs under your
          account. Notify us immediately at <a href="mailto:support@myogen.app" style={{ color: '#00F0FF' }}>support@myogen.app</a> if
          you believe your account has been compromised.
        </Section>

        <Section title="Premium subscriptions">
          Premium access is billed on a recurring monthly basis via PayPal. You may cancel at any time from your
          Account page or by contacting us. Cancellation takes effect at the end of the current billing period — you
          retain access to Premium features until then.
        </Section>

        <Section title="Acceptable use">
          You agree not to misuse Myogen. Prohibited conduct includes attempting to reverse-engineer the service,
          scraping or harvesting data, uploading harmful or illegal content, and any action that could damage,
          overload, or impair the platform or other users' experience.
        </Section>

        <Section title="Intellectual property">
          All content, branding, and code within Myogen is the property of Myogen and its licensors. You may not
          copy, reproduce, or distribute any part of the service without prior written permission.
        </Section>

        <Section title="Disclaimer of warranties">
          Myogen is provided "as is" without warranties of any kind. We do not guarantee that the service will be
          uninterrupted, error-free, or that results obtained from it will be accurate or reliable.
        </Section>

        <Section title="Limitation of liability">
          To the fullest extent permitted by law, Myogen and its operators shall not be liable for any indirect,
          incidental, special, or consequential damages arising from your use of — or inability to use — the service.
        </Section>

        <Section title="Governing law">
          These terms are governed by the laws of the Republic of South Africa. Any disputes shall be subject to the
          exclusive jurisdiction of the courts of South Africa.
        </Section>

        <Section title="Contact" last>
          Questions about these terms? Email us at{' '}
          <a href="mailto:legal@myogen.app" style={{ color: '#00F0FF' }}>
            legal@myogen.app
          </a>
          .
        </Section>
      </main>
    </div>
  );
}

function Section({ title, children, last }) {
  return (
    <section style={{ marginBottom: last ? 0 : '36px' }}>
      <h2 style={{
        fontFamily: 'Manrope, sans-serif',
        fontSize: '1rem',
        fontWeight: 600,
        marginBottom: '10px',
        letterSpacing: '-0.015em',
      }}>
        {title}
      </h2>
      <p style={{ color: '#A1A1AA', lineHeight: 1.75, fontSize: '14px' }}>{children}</p>
    </section>
  );
}
